### ISSUE TITLE
 denoising training dataset

### ISSUE THREAD

**Issue by 17346604401** [swz30/Restormer#12]
well done ! But can you tell me about your denoising-working ,what dataset your used? real training dataset and Gaussian Denoising dataset. Thank you very much!

**Comment by adityac8** [comment]
<img width="338" alt="image" src="https://user-images.githubusercontent.com/19192257/144656820-e1855e75-8b4d-42da-b227-50ff790ccad9.png">

**Comment by adityac8** [comment]
Hi @17346604401 

Please find the details about Gaussian and Real Image Denoising.
Further details about datasets for other tasks are available in the Supplementary Material.

Thanks

**Comment by hellogry** [comment]
I want to know about the training dataset is the Train400 which is like the DnCNN method?
