### ISSUE TITLE
MDTA

### ISSUE THREAD

**Issue by vztu** [swz30/Restormer#13]
Hi @swz30,

Thanks for the great work!

The multi-Dconv head transposed attention (MDTA) you proposed is not a **spatial-attention** mechanism, right? So the efficiency is only attained by switching the original attention applied on spatial dim to channel dim, which is always fixed regardless of image sizes. If this holds true, unlike attention in ViT, MDTA cannot perform long-range (or global) interaction across the spatial dim, correct?

**Comment by swz30** [comment]
Thanks for the question. 
Yes, the attention is applied by switching dimensions in MDTA. Here, the relationships are modeled per feature dimension i.e., how one feature covaries with another feature dimension. This calculation implicitly includes the spatial relationships for each individual dimension via simple products followed by summation. Note that both the Gram matrix (as obtained in original self-attention) and the Covariance matrix (obtained in our case) are related to each other and can provide the same diagonal matrix (and hence the same singular values) as a result of SVD. The Eigenvectors of covariance matrix (U) are also related to the Eigenvectors of gram matrix (V) by U = XV.
