### ISSUE TITLE
Access denied during downloading the DND denoising dataset.

### ISSUE THREAD

**Issue by Austin-111** [swz30/Restormer#21]
Hi, thank you for your great work!
I met a permission problem during downloading the DND denoising dataset. But I still am able to access the file from the browser. I wonder if changing permission can fix it.
![image](https://user-images.githubusercontent.com/37174690/158053244-d442e283-67db-45e3-8ad8-00f252534608.png)

**Comment by adityac8** [comment]
Hi @Austin-111 

I tried downloading the DND test dataset again and was able to do so on a new machine. Could you check again using `gdrive` and only downloading DND dataset using
```
python download_data.py --data test --dataset DND --noise real
```

Thanks

**Comment by Austin-111** [comment]
Hi @adityac8 

Thanks for your quick reply! I used `gdown` instead of `gdrive` because I didn't successfully install `gdrive` following the guide. I have downloaded GoPro, HIDE, RealBlur-R, RealBlur-J, Rain13k, and SIDD by using `gdown`. Now I have download DND from the browser. 

Thanks again!
