### ISSUE TITLE
add model to Huggingface

### ISSUE THREAD

**Issue by AK391** [swz30/Restormer#22]
Hi, would you be interested in adding Restormer to [Hugging Face Hub](https://huggingface.co/models)? The Hub offers free hosting, and it would make your work more accessible and visible to the rest of the ML community. We can setup an organization or a user account under which restormer can be added similar to github.

Example from other organizations:
Keras: https://huggingface.co/keras-io
Microsoft: https://huggingface.co/microsoft
Facebook: https://huggingface.co/facebook

Example spaces with repos:
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/akhaliq/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

and here are guides for adding spaces/models/datasets to your org

How to add a Space: https://huggingface.co/blog/gradio-spaces
how to add models: https://huggingface.co/docs/hub/adding-a-model
uploading a dataset: https://huggingface.co/docs/datasets/upload_dataset.html

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation.

**Comment by swz30** [comment]
Hi @AK391 

Thank you. If possible, could you please create the Gradio space for Restormer. Here is a [demo](https://github.com/swz30/Restormer#quick-run) that might be helpful in setting up the space. Please add the option buttons for the following restoration tasks: (1) Defocus Deblurring, (2) Real Image Denoising,  (3) Motion Deblurring, and (4) Deraining.

**Comment by swz30** [comment]
Web demo on gradio-spaces is now available:  [![Hugging Face Spaces](https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-Spaces-blue)](https://huggingface.co/spaces/swzamir/Restormer)

**Comment by AK391** [comment]
@swz30 thanks for making the Gradio Demo, great work, would you be interested in updating the demo using gradio blocks for the Gradio blocks competition this month: https://huggingface.co/Gradio-Blocks or adding another model, thanks
