### ISSUE TITLE
Problems about training dual_pixel defocus deblur

### ISSUE THREAD

**Issue by FlyFish-space** [swz30/Restormer#23]
I ran the training code of DualPixel in your way, and there is an error. The error is as follows:

` ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2200930) of binary: (my python path) `
` ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed `
` INFO:torch.distributed.elastic.agent.server.api:Local worker group finished (FAILED). Waiting 300 seconds for other agents to finish` 
  
This error should be related to distributed training. I use two gpus for distributed training and  modify [Restormer/train.sh]and [DefocusDeblur_Single_8bit_Restormer.yml].

**Comment by adityac8** [comment]
Hi @FlyFish-space 

For training dual-pixel defocus deblurring task and run on 2 GPUs,

1. Modify [train.sh](https://github.com/swz30/Restormer/blob/main/train.sh) as follows 
```
python -m torch.distributed.launch --nproc_per_node=2 --master_port=4321 basicsr/train.py -opt $CONFIG --launcher pytorch
```

2. Modify `num_gpu: 2`
https://github.com/swz30/Restormer/blob/a4c1f8883caf39d6d4887d43fa5a1fa85421dd97/Defocus_Deblurring/Options/DefocusDeblur_DualPixel_16bit_Restormer.yml#L5

4. Download the dataset using [download_data.py](https://github.com/swz30/Restormer/blob/main/Defocus_Deblurring/download_data.py)

5. Run the train file
```
cd Restormer
./train.sh Defocus_Deblurring/Options/DefocusDeblur_DualPixel_16bit_Restormer.yml
```

If you are still unable to run and get any errors, please paste the full output here.

Thanks

**Comment by FlyFish-space** [comment]
OK. Thanks
