### ISSUE TITLE
problem on the step ”Install gdrive using“

### ISSUE THREAD

**Issue by ZYQii** [swz30/Restormer#24]
Dear author，I met a problem when input the code "go get github.com/prasmussen/gdrive"

package golang.org/x/oauth2/google: unrecognized import path "golang.org/x/oauth2/google" (https fetch: Get https://golang.org/x/oauth2/google?go-get=1: dial tcp 172.217.163.49:443: i/o timeout)

I want to know how to solve this.THANKS!

**Comment by adityac8** [comment]
Hi @ZYQii 

Could you please tell which `go` version are you using.

Thanks

**Comment by ZYQii** [comment]
Hi @adityac8 

$ go version
go version go1.11.1 linux/amd64

still not work

**Comment by swz30** [comment]
Hi @ZYQii,

Instead of gdrive, you can try gdown; See this #21
