### ISSUE TITLE
About the training

### ISSUE THREAD

**Issue by SunYJLU** [swz30/Restormer#26]
How to solve the error of create_dataloader, create_dataset in _init_.py in the train.py file？
Also what is the difference between training on basicsr documents and training on specific tasks (e.g. Deraining)?

**Comment by adityac8** [comment]
Hi @SunYJLU 

Please provide the full output of your error so that we can help you with it.

Thanks

**Comment by SunYJLU** [comment]
In the utils/train.py file, the statements from basicsr.data import create_dataloader, create_dataset and creat_xxxxxxxx in from basicsr.models import create_model are marked in red, indicating that pycharm cannot be referenced from the init.py file

**Comment by Yan98** [comment]
train.py is not placed in a correct director at least for me. use "mv ./basicsr/train.py ." and change train.sh
