### ISSUE TITLE
Question about the baseline model

### ISSUE THREAD

**Issue by cambridgeinch** [swz30/Restormer#27]
Dear Authors, 
  Congratulations to you for the paper has been acepted as Oral in CVPR 2022.
  Here, I have a question about the code. 
In Section 4.5 'Ablation Studies', Table.7 compares the performance of baseline, multi-head attention, FFN and overall model. The baseline's component is Unet with Resblocks (EDSR model). Is the number of blocks [4, 6, 6, 8] in overall network same as the number of blocks in baseline model? And where can I find the baseline model code? Is that in 'https://github.com/xinntao/BasicSR/blob/master/basicsr/archs/edsr_arch.py'?

**Comment by swz30** [comment]
Hi @cambridgeinch,

Yes, the number of blocks is ```[4,6,6,8]``` in the baseline as well; but we set ```dim=40```, as the regular Convs are heavier. Here is the code snippet for Resblock:
```
class Resblock(nn.Module):
    def __init__(self, dim, bias):
        super(Resblock, self).__init__()

        self.body = nn.Sequential(nn.Conv2d(dim, dim, kernel_size=3, stride=1, padding=1, bias=False),
                                  nn.LeakyReLU(0.2),
                                  nn.Conv2d(dim, dim, kernel_size=3, stride=1, padding=1, bias=False)
                                 )

    def forward(self, x):
        x = x + self.body(x)
        return x
```
