### ISSUE TITLE
Cuda out Of memory error

### ISSUE THREAD

**Issue by zelenooki87** [swz30/Restormer#29]
For real denoising task, on photos bigger than 4Mpx code returns this error.
`RuntimeError: CUDA out of memory. Tried to allocate 7.62 GiB (GPU 0; 12.00 GiB total capacity; 5.33 GiB already allocated; 4.64 GiB free; 5.35 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

Is there any trick to get it working properly with RTX 3060? 

Thanks

**Comment by zelenooki87** [comment]
As project says "High-Resolution Image Restoration"... I thought it will work with well midrange GPUs...
After modifing batch size and image size etc...another shape errors ocurs.... so,
please add --tile option argument in code
tnx

**Comment by swz30** [comment]
Hi @zelenooki87,

The proposed Restormer can deal with the standard high-definition images (1280x720) on regular GPUs (Titan XP, etc). To test on even larger images, we have now added the ```--tile``` option in [demo.py](https://github.com/swz30/Restormer/blob/main/demo.py). Here is an example usage:

```
python demo.py --task Real_Denoising --input_dir './demo/degraded/noisy.png' --result_dir './demo/restored/' --tile 720 --tile_overlap 32
```

Hope it helps.
