### ISSUE TITLE
Happy to see the HINet codebase helps your research!

### ISSUE THREAD

**Issue by mayorx** [swz30/Restormer#32]
Don't you think that it is appropriate to add a link to the HINet (e.g. https://github.com/megvii-model/HINet), thanks!

**Comment by swz30** [comment]
Hi @mayorx 

The original toolbox [basicsr](https://github.com/xinntao/BasicSR) was already in the acknowledgments. Now HINet is also added.

**Comment by mayorx** [comment]
Hi, swz30,
Thanks a lot!
