### ISSUE TITLE
The url of Gassian denoising datasets are invalid, please provide the new url, thanks.

### ISSUE THREAD

**Issue by Einstone-rose** [swz30/Restormer#39]

**Comment by swz30** [comment]
Hi @Einstone-rose 

The links are working on my end, please try again. If you are having issues with ```download_data.py``` script, you can use **direct** google drive links provided in the comments here https://github.com/swz30/Restormer/blob/55b1f83a60c3d874953b6affba5c0050ad1caa62/Denoising/download_data.py#L30
