### ISSUE TITLE
Loss function and supp

### ISSUE THREAD

**Issue by jiaaihhy** [swz30/Restormer#4]
In this paper , I dont find the defination of loss function, could you tell me the loss function of restormer.   
and where can i find the supplement of this paper.
thank you

**Comment by swz30** [comment]
Hi @jiaaihhy 

We use the L1 loss for network optimization. 

We will release the supplementary material here on Github in a couple of days.

**Comment by swz30** [comment]
Hi @jiaaihhy 

The supplementary material is released [here](https://drive.google.com/file/d/13AgJJEjYRNrUuMWkiRWPo_19F6xCzgIV/view?usp=sharing).
