### ISSUE TITLE
Question about result.

### ISSUE THREAD

**Issue by LLlio** [swz30/Restormer#40]
Thanks for your outstanding work. I have a question about your deraining result. I tested deraining.pth weights you provided, and this is its results:
![image](https://user-images.githubusercontent.com/84756327/166137112-0bce23d2-8891-49bd-823d-4e63f279e7f5.png)
It is much lower than results in your paper. Can you explain it and show more details of your deraining results?
Thank you!

**Comment by swz30** [comment]
Hi @LLlio 

I just checked on my side and I confirm that if you follow the steps provided [here ](https://github.com/swz30/Restormer/tree/main/Deraining#evaluation), the results are reproducible.  Make sure to use ```evaluate_PSNR_SSIM.m``` for PSNR/SSIM calculation.
