### ISSUE TITLE
Train from pre-trained model (like ImageNet1K) or random initialization model?

### ISSUE THREAD

**Issue by guanhuankang** [swz30/Restormer#46]
Hello,

When training the Resformer, do you train it from a random initialization model or pre-trained it on ImageNet1K/21K as ResNeXt series do? According to my understanding, it is trained without additional data. For example, in derain task, only use the Rain13K to train the random initialization model for 300K iterations. Am I right? Thanks!

**Comment by swz30** [comment]
Yes, the model is trained from scratch.
