### ISSUE TITLE
The number of channels do not match before/after pixel unshuffle/shuffle?

### ISSUE THREAD

**Issue by guanhuankang** [swz30/Restormer#47]
I am wondering that the number of channels should become 4 times (1/4 times) after applying pixel unshuffle (pixel shuffle) with downscale (upscale x2). But in Fig.1, the number of channels is double (half) before applying pixel unshuffle (pixel shuffle).

**[My question]**
Is there another layer (like conv_1x1) next to the upsampling/downsample operator to adjust the number of channels (but is not mentioned in Fig.1)? Am I right? Thank you for your time!

Here, I paste my understanding of pixel shuffle. The number of channels changes in r*r scale.
<img width="673" alt="image" src="https://user-images.githubusercontent.com/31817414/167443754-a70d685c-8664-4e60-83b6-3980ecf9be3c.png">

**Comment by swz30** [comment]
Yes, we adjust the channels before pixel shuffle and unshuffle operation: https://github.com/swz30/Restormer/blob/55b1f83a60c3d874953b6affba5c0050ad1caa62/basicsr/models/archs/restormer_arch.py#L170
