### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by jiaaihhy** [swz30/Restormer#5]
In Gopro deblurring, I want to know How many gpus were used and how long were they trained in 
[patchsize 128, batchsize 64].

**Comment by baiyu12345** [comment]
haha, I think you need about 20 V-100 32G.

**Comment by swz30** [comment]
Hi @jiaaihhy,

We have released the training codes. By default, the training script uses 8 NVIDIA Tesla V100 GPUs. To use any other number of GPUs, modify [Restormer/train.sh](https://github.com/swz30/Restormer/blob/main/train.sh) and the YAML file corresponding to each task.
