### ISSUE TITLE
Difference between the MDTA block and the RL-NL module in SAN

### ISSUE THREAD

**Issue by 11710615** [swz30/Restormer#52]
Thanks for sharing the exciting work. One problem is that your work about the MDTA block seems similar with RL-NL module in SAN for super-resolution task. What's the difference between them.

**Comment by Mytttttttt** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
