### ISSUE TITLE
I wrote code in Python to test PSNR and SSIM, why is the PSNR and SSIM I tested in Python lower than those in the paper? PSNR is about 1.2dB lower

### ISSUE THREAD

**Issue by dante1024** [swz30/Restormer#55]
I wrote code in Python to test PSNR and SSIM, why is the PSNR and SSIM I tested in Python lower than those in the paper? PSNR is about 1.2dB lower

**Comment by adityac8** [comment]
The Python code for getting a similar PSNR for the detaining task on Y channel can be found at https://github.com/kuijiang94/MSPFN/issues/7#issuecomment-656785181
