### ISSUE TITLE
DeamNet and AINDNet results in Real image denoising

### ISSUE THREAD

**Issue by it-hao** [swz30/Restormer#7]
Hello, I doubt the results showed in real image denoising are wrong.
The DeamNet and AINDNet use SIDD **benchmark** to test. However, in your paper, you utilize the results of the SIDD benchmark to compare the results tested in SIDD validation datasets. MIRNet and MPRNet also can find the same problem. 
so why not directly compare the results of the Benchmark dataset? Like the DND dataset, the results can be obtained on websites.

**Comment by swz30** [comment]
Hi @it-hao 

The authors of RIDNet initially reported results on the validation set. Following RIDNet, the other works (CycleISP, VDN, DANet, MIRNet, SADNet, MPRNet, uformer) also performed evaluation on the validation set.  

Thank you for pointing the error in DeamNet and AINDNet results. We will update the numbers in the ArXiv version. Here are the comparisons of DeamNet, AINDNet and Restormer on the validation and test sets of SIDD dataset.


| SIDD Dataset (PSNR/SSIM)| DeamNet | AINDNet|Restormer|
| :---: | :---: | :---: | :---: |
| Validation Set | 39.47/0.957 | 39.08/0.954 | 40.02/0.960|
| Test Set (Server) | 39.35/0.955 | 38.95/0.952 | 39.86/0.959|

I hope it helps.

**Comment by it-hao** [comment]
> 

great
