### ISSUE TITLE
Questions about the quantitative results of other methods?

### ISSUE THREAD

**Issue by chenquan-hdu** [swz30/Restormer#76]
Hi, 
How are the quantitative results calculated for the other methods in Restormer Table 1? Are you quoting their results directly or are you retraining them?

Looking forward to your reply. Thank you!

**Comment by adityac8** [comment]
For Image Deraining, we follow the same convention as MSPFN and utilize the Table provided in their paper.

**Comment by chenquan-hdu** [comment]
Thank you, 
I have downloaded others quantitative results from MSPFN.
Besides, the Restormer only uses Rain100L as validation in the training stage?  Or uses (rain100L+rain100H+test100+test1200+test2800) datasets as validation in the training stage?

Thank you again, and looking forward to your reply.

**Comment by adityac8** [comment]
We cross validate our trainind on `Rain100L` dataset. You can change it to use another dataset here
https://github.com/swz30/Restormer/blob/733ceb2e5cdab8074d59a8d440c645a11b5dd334/Deraining/Options/Deraining_Restormer.yml#L46-L47
