### ISSUE TITLE
Question about training denoising model

### ISSUE THREAD

**Issue by Andrew0613** [swz30/Restormer#78]
I followed the instructions and conducted 2 Gaussian color image denoising experiments where sigma=15 and 50. But I can't reproduce the same PSNR value as paper shows. 
Here are my results:
sigma=15
For CBSD68 dataset Noise Level 15 PSNR: 34.398237 
For Kodak dataset Noise Level 15 PSNR: 35.439437
For McMaster dataset Noise Level 15 PSNR: 35.556497
For Urban100 dataset Noise Level 15 PSNR: 35.058984
sigma=50
For CBSD68 dataset Noise Level 50 PSNR: 28.586302
For Kodak dataset Noise Level 50 PSNR: 29.967525
For McMaster dataset Noise Level 50 PSNR: 30.237451
For Urban100 dataset Noise Level 50 PSNR: 29.891585

Did I miss some important details?

**Comment by Mytttttttt** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
