### ISSUE TITLE
datasets download

### ISSUE THREAD

**Issue by yang-jack-png** [swz30/Restormer#86]
”Authentication needed 
Go to the following url in your browser: https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=367116221053-7n0vf5akeru7on6o2fjinrecpdoe99eg.apps.googleusercontent.com&redirect_u ri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=state“ 
The above is the problem I encountered, but when I follow the url in my browser. The browser would display the following problems: 
Access blocked: project-367116221053’s request is invalid yjc980503@gmail.com You can’t sign in because project-367116221053 sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384) If you are a developer of project-367116221053, see [error details](https://accounts.google.com/). Error 400: invalid_request. 
Could you give me some suggestions, than you?

**Comment by yang-jack-png** [comment]
”Authentication needed Go to the following url in your browser: https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=367116221053-7n0vf5akeru7on6o2fjinrecpdoe99eg.apps.googleusercontent.com&redirect_u ri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=state“ The above is the problem I encountered, but when I follow the url in my browser. The browser would display the following problems: Access blocked: project-367116221053’s request is invalid yjc980503@gmail.com You can’t sign in because project-367116221053 sent an invalid request. You can try again later, or contact the [developer](https://accounts.google.com/) about this issue. [Learn more about this error](https://support.google.com/accounts/answer/12379384) If you are a developer of project-367116221053, see [error details](https://accounts.google.com/). Error 400: invalid_request. Could you give me some suggestions, than you?

**Comment by XuJinglinn** [comment]
I encountered the same problem. How did you solve this problem in the end?

**Comment by biter0088** [comment]
I encountered the same problem. How did you solve this problem in the end?
```bash
DPDD Testing Data!
Authentication needed
Go to the following url in your browser:
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=367116221053-7n0vf5akeru7on6o2fjinrecpdoe99eg.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&state=state

Enter verification code: 0088
Failed getting oauth client: Failed to exchange auth code for token: oauth2: "invalid_grant" "Malformed auth code."
Extracting DPDD test set...
Traceback (most recent call last):
  File "download_data.py", line 43, in <module>
    shutil.unpack_archive('Datasets/test.zip', 'Datasets')
  File "/home/xiu/anaconda3/envs/simdeblur/lib/python3.8/shutil.py", line 1249, in unpack_archive
    func(filename, extract_dir, **kwargs)
  File "/home/xiu/anaconda3/envs/simdeblur/lib/python3.8/shutil.py", line 1136, in _unpack_zipfile
    raise ReadError("%s is not a zip file" % filename)
shutil.ReadError: Datasets/test.zip is not a zip file
```
