### ISSUE TITLE
Hello guys, did any one meet this Issue "ModuleNotFoundError: No module named 'typing_extensions'"

### ISSUE THREAD

**Issue by VagoLapis** [swz30/Restormer#88]
![image](https://github.com/swz30/Restormer/assets/139826997/5a0627fe-91b0-401c-b90b-d32b78d7fc2b)
请问有人遇到过No module named 'typing_extensions'的问题吗，即使已经安装了这个模块

**Comment by bnm6900030** [comment]
没有遇到这个问题过,正常安装后是可以跑的,而且这个论文的工作是少有的能和paper对应上的,比它强的网络大多都复现不了效果.

**Comment by VagoLapis** [comment]
感谢您的回复，这个问题经过仔细查看后，是使用conda安装pytorch导致的版本问题，目前已经解决。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "swz30/Restormer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月24日(星期一) 下午3:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [swz30/Restormer] Hello guys, did any one meet this Issue "ModuleNotFoundError: No module named 'typing_extensions'" (Issue #88)





 
没有遇到这个问题过,正常安装后是可以跑的,而且这个论文的工作是少有的能和paper对应上的,比它强的网络大多都复现不了效果.

**Comment by VagoLapis** [comment]
【已解决】 这个报错是使用conda安装pytroch时引起的pytroch版本不一致，使用pip安装就好。
[solved] This issue, upon closer inspection, is a version issue caused by installing pytorch using conda.
