### ISSUE TITLE
About  layer normalization code

### ISSUE THREAD

**Issue by zzg-tju** [swz30/Restormer#9]
There are some discrepancies between the layer normalization that I understand and the implementation method in the code. I hope someone can answer my doubts:

I understand layer normalization: 
input X, dimension B C H W, calculate the mean variance of length B for each B, multiply the weight and bias of length B

Layer normalization in the Restomer code: 
input X, dimension B C H W, calculate the mean variance of B H*W dimension, multiply the weight and bias of length C

**Comment by adityac8** [comment]
Hi @zzg-tju 

Our Layer Norm implementation is consistent with previous works in Vision Transformers such as [timm](https://github.com/rwightman/pytorch-image-models/blob/f7d210d759beb00a3d0834a3ce2d93f6e17f3d38/timm/models/vision_transformer.py#L220) and [segformer](https://github.com/lucidrains/segformer-pytorch/blob/b49efeae7b4fda4f9daf01e8efab91edcc9f42f0/segformer_pytorch/segformer_pytorch.py#L30).

For further details, you can have a look [here](https://github.com/pytorch/pytorch/issues/51455).

Thanks
